version: '3.8'

services:
  frontend:
    image: xxmymxue/lazycatapp-frontend:0.0.3
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - lazycat-app-network

  backend:
    image: xxmymxue/lazycatapp-backend:0.0.3
    ports:
      - "9999:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - lazycat-app-network
      
networks:
  lazycat-app-network:
    driver: bridge
